### PR TITLE
Added `firmata.py` as a template and instructions kind of file for how one can utilize networking with arduinos

### PR DESCRIPTION
**Pull request by dharmik2319**
From Dharmik Kaku

### CODE REVIEW

**Comment by dharmik2319** [comment]
link to firmata.js if you wish to use that:
- [firmata.js](https://github.com/firmata/firmata.js/)
- [blink example](https://github.com/firmata/firmata.js/blob/master/packages/firmata.js/examples/blink.js)

edit: there also is a typescript implementation apparently, [this](https://freedium.cfd/@nathsantos2703/arduino-connection-with-nodejs-and-typescript-afdf78e14a75) is a startup guide kinda thing and [this](https://www.npmjs.com/package/johnny-five) is its npm package

**Comment by dharmik2319** [comment]
you will first need to upload the StandardFirmata sketch. to do that:
- in Arduino IDE, click File in the ribbon.
- Examples > StandardFirmata
- Upload that sketch
- After that you may run the python code (3.10 or below)

**Comment by Jay-Karia** [comment]
After scanning, how can I get the input data ?

**Comment by dharmik2319** [comment]
I thought you knew that so i didnt bother putting it in the code. Let me see what i can do

**Comment by dharmik2319** [comment]
ok, after a bit of research, you would need to write some custom code using the firmata library instead of using the readymade example. but dont worry, [look here](https://forum.arduino.cc/t/arduino-libraries-in-python/1009731/31) for reference

**Comment by Jay-Karia** [comment]
> I thought you knew that so i didnt bother putting it in the code. Let me see what i can do

I have never worked on Arduino Projects

**Comment by Jay-Karia** [comment]
And, how is it possible to call the api without internet connection. You are just using `reuqests` module.

**Comment by dharmik2319** [comment]
> And, how is it possible to call the api without internet connection. You are just using `reuqests` module.

- well, a self hosted api does not need an internet connection. just like i am doing in our project.
- even if you are not using a self hosted api, but one which connects to the internet, it will work, because the `requests` module will send a request from the PC (which is connected to the internet) when the code sees that the data sent through rfid through the arduino is valid.

**Comment by dharmik2319** [comment]
> > I thought you knew that so i didnt bother putting it in the code. Let me see what i can do
> 
> I have never worked on Arduino Projects

sorry, i was not aware of that. still, you can try and fit the code to your needs. it is simple enough, tbh.

**Comment by Jay-Karia** [comment]
> > And, how is it possible to call the api without internet connection. You are just using `reuqests` module.
> 
> * well, a self hosted api does not need an internet connection. just like i am doing in our project.
> * even if you are not using a self hosted api, it will work, because the `requests` module will send a request from the PC (which is connected to the internet) when the code sees that the data sent through rfid through the arduino is valid.

The API which I am using needs a connection to the database to perform operations related to it.

To connect the database, it requires internet connection.

**Comment by Jay-Karia** [comment]
> > > I thought you knew that so i didnt bother putting it in the code. Let me see what i can do
> > 
> > 
> > I have never worked on Arduino Projects
> 
> sorry, i was not aware of that. still, you can try and fit the code to your needs. it is simple enough, tbh.

I know the basics of python, but not specific to Arduino

**Comment by dharmik2319** [comment]
> The API which I am using needs a connection to the database to perform operations related to it.
To connect the database, it requires internet connection.

> even if you are not using a self hosted api, but one which connects to the internet, it will work, because the requests module will send a request from the PC (which is connected to the internet) when the code sees that the data sent through rfid through the arduino is valid.

you may close the pr if you want

**Comment by Jay-Karia** [comment]
Our main aim was to call the api with internet connection without any external device (such as Internet module, or laptop).
You suggested to use firmata, but now it seems that it needs an external device for internet connection, which was our problem... but anyways

Thanks for your time.

**Comment by dharmik2319** [comment]
Oh, seems to be a case of miscommunication. I thought you said that you were fine with an Arduino being plugged into a PC.

**Pull request closed without merging**
